# Dockerfile.frontend
FROM python:3.10-slim

# תיקייה שבה יפעל הקוד
WORKDIR /app

# התקנת הספריות מה-frontend
COPY frontend/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

# העתקת קוד ה-frontend
COPY frontend/ ./frontend/

# פתיחת הפורט של Gradio
EXPOSE 7860

# הפקודה שמריצה את ה-UI
CMD ["python", "-m", "frontend.app"]
