FROM python:3.10-slim
ENV PIP_REQUIRE_HASHES=0
WORKDIR /app

COPY consumer/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY consumer/consumer.py /app/consumer.py

CMD ["python", "consumer.py"]
